[tool.poetry]
name = "pyplier"
version = "0.13.0"
description = "Python reimplementation of PLIER"
authors = ["milescsmith <mileschristiansmith@gmail.com>"]
license = "MPL2.0"

[tool.poetry.dependencies]
python = "^3.9,<3.10"
numpy = ">=1.21"
pandas = "^1.4"
scipy = "^1.7"
statsmodels = "^0.13"
joblib = "^1.1"
rich = "^10.13"
pysmooth = "^1.1.3"
icontract = "^2.6.0"
glmnet = "^2.2.1"
pylint = "^2.12.2"
tqdm = "^4.62.3"
coloredlogs = "^15.0.1"
glmnet-py = "^0.1.0-beta.2"
enlighten = "^1.10.2"
typeguard = "^2.13.3"
structlog = "^21.5.0"
seaborn = "^0.11.2"
scikit-learn = "^1.1.1"

[tool.poetry.dev-dependencies]
mypy = "flake8"
flake8 = "^4.0.1"
ipykernel = "^6.4.2"
isort = "^5.10.0"
nox = "^2022.0.0"
hypothesis = "^6.24.2"
pytest = "^6.2.5"
nox-poetry = "^0.8.6"
black = {version = ">=22.1", extras = ["all"]}
importlib-resources = { version = "^5.4.0", python = "~3.8" }
jupyterlab = "^3.2.5"
xeus-python = "^0.13.5"
icontract-hypothesis = "^1.1.7"
matplotlib = "^3.5.1"
ipython = ">=8.1.0"
ipywidgets = "^7.6.5"
jupyterlab-widgets = "^1.0.2"
dill = "^0.3.4"
pyicontract-lint = "^2.1.4"
yapf = "^0.32.0"
deepdiff = "^5.8.1"
bandit = "^1.7.4"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
