[tool.poetry]
name = "pyplier"
version = "0.1.0"
description = "Python reimplementation of PLIER"
authors = ["milescsmith <mileschristiansmith@gmail.com>"]
license = "MPL2.0"

[tool.poetry.dependencies]
python = "^3.8,<3.10"
numpy = "^1.20.3"
pandas = "^1.3.4"
scipy = "^1.7.1"
numba = "^0.54.1"
statsmodels = "^0.13.0"
joblib = "^1.1.0"
rich = "^10.13.0"

[tool.poetry.dev-dependencies]
mypy = "flake8"
flake8 = "^4.0.1"
ipykernel = "^6.4.2"
isort = "^5.10.0"
nox = "^2021.10.1"
hypothesis = "^6.24.2"
pytest = "^6.2.5"
nox-poetry = "^0.8.6"
black = {version = "^21.10b0", extras = ["all"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
